permalink   : /:title/
markdown    : rdiscount
highlighter : pygments

paginate: 6
comments: true
paginate_path: "/page/:num"

baseurl: "" # change to empty string ""
domain_name: jstoebel.com
google_analytics: UA-52446115-1

source:      source
destination: _site

sass:
  sass_dir: source/assets/_sass
# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Jacob Stoebel
title: Jacob Stoebel | Software Developer
description: "Software developer and xkcd forwarder. Python, Ruby, JavaScript etc."
meta_description: "Software developer and xkcd forwarder. Python, Ruby, JavaScript etc."
meta_keywords: "site, website, softwware, software developer, python, djangp, ruby, ruby on rails, javascript, frontend, front-end, html5, css3, jquery, react"

production_url: http://www.jstoebel.com
repo: https://github.com/jstoebel/jstoebel.github.com
# disqus_shortname: "nandothemes"
rss_path: source/
author:
  name      : Jacob Stoebel
  image     : /assets/images/author.jpg
  email     : jstoebel@gmail.com
  url       : http://www.jstoebel.com
  twitter   : http://twitter.com/jstoebel
  github    : http://github.com/jstoebel
  linkedin  : https://www.linkedin.com/in/jacob-stoebel-71705223?trk=nav_responsive_tab_profile
  bio       : "I am a software developer living in Berea, KY. I spend my days writing web applications (Ruby, Python, JavaScript), working with data, and leveling up as a software engineer. I work and study at Berea College. This is my blog."

# thought
thought:
  text: I have no special talent. I am only passionately curious.
  author: Albert Einstein

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
